"""initial_tables

Revision ID: 1b7b173d9c74
Revises: 1a0f7a820e41
Create Date: 2026-04-24 00:30:03.159180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7b173d9c74'
down_revision: Union[str, Sequence[str], None] = '1a0f7a820e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('description', sa.String(), nullable=True))
    op.add_column('games', sa.Column('game_type', sa.String(), nullable=True))
    op.add_column('games', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'content')
    op.drop_column('games', 'game_type')
    op.drop_column('games', 'description')
    # ### end Alembic commands ###
