"""initial_tables

Revision ID: 73e0299ce9b2
Revises: 1b7b173d9c74
Create Date: 2026-04-25 17:51:41.341468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e0299ce9b2'
down_revision: Union[str, Sequence[str], None] = '1b7b173d9c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_subtype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_subtype')
    # ### end Alembic commands ###
